# Generated by Django 5.0 on 2024-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taifa_sacco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprediction',
            name='risk_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
